import type { MetadataRoute } from 'next';
import { db } from '@/server/db';
import { absoluteUrl } from '@/lib/seo';

/**
 * Split sitemap, served under `/sitemap/<section>.xml`.
 *
 * Next's `sitemap.ts` file convention always resolves to a `<urlset>` —
 * there is no way to make it emit a real `<sitemapindex>` (see
 * `resolveRouteData` in next's metadata-route loader). `generateSitemaps()`
 * is the framework's supported answer to "more than one sitemap": each
 * returned `id` becomes its own `/sitemap/<id>.xml` route, generated by
 * calling the default export below with that `id`. `robots.ts` lists every
 * resulting URL under `Sitemap:` — multiple `Sitemap:` lines in robots.txt
 * is Google/Bing's documented alternative to a sitemap index file, so
 * discovery works the same either way. See docs/SEO.md for the full
 * writeup and the 40,000-URL-per-file pagination this enables for
 * `products-N`.
 */

export const PRODUCT_PAGE_SIZE = 40_000;

function activeProductWhere(now: Date) {
  // Never list a DRAFT, ARCHIVED, or future-scheduled product.
  //
  // NOTE: this deliberately uses `expiresAt: { gt: now } OR null`, not
  // `NOT: { expiresAt: { lte: now } }` — SQL's three-valued logic means
  // `NOT (expires_at <= now)` evaluates to NULL (never true) for a row
  // where `expires_at IS NULL`, silently excluding every product that has
  // no expiry at all. Same reasoning applies to `publishAt` below.
  return {
    status: 'ACTIVE' as const,
    OR: [{ publishAt: null }, { publishAt: { lte: now } }],
    AND: [{ OR: [{ expiresAt: null }, { expiresAt: { gt: now } }] }],
  };
}

export async function getProductSitemapPageCount(): Promise<number> {
  try {
    const count = await db.product.count({ where: activeProductWhere(new Date()) });
    return Math.max(1, Math.ceil(count / PRODUCT_PAGE_SIZE));
  } catch {
    return 1;
  }
}

export const STATIC_SECTION_IDS = ['static', 'categories', 'brands', 'blog'] as const;

export async function generateSitemaps(): Promise<{ id: string }[]> {
  const productPages = await getProductSitemapPageCount();
  const ids: string[] = [...STATIC_SECTION_IDS];
  for (let i = 0; i < productPages; i++) ids.push(`products-${i}`);
  return ids.map((id) => ({ id }));
}

async function staticEntries(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  const entries: MetadataRoute.Sitemap = [
    { url: absoluteUrl('/'), lastModified: now, changeFrequency: 'daily', priority: 1 },
    { url: absoluteUrl('/blog'), lastModified: now, changeFrequency: 'daily', priority: 0.5 },
    { url: absoluteUrl('/contact'), lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
  ];

  try {
    const pages = await db.page.findMany({
      where: { status: 'PUBLISHED' },
      select: { slug: true, updatedAt: true },
    });
    for (const p of pages) {
      entries.push({
        url: absoluteUrl(`/p/${p.slug}`),
        lastModified: p.updatedAt,
        changeFrequency: 'monthly',
        priority: 0.4,
      });
    }
  } catch {
    // Fail open — the rest of the sitemap is still worth serving.
  }

  return entries;
}

async function categoryEntries(): Promise<MetadataRoute.Sitemap> {
  try {
    const rows = await db.category.findMany({
      where: { isActive: true },
      select: { slug: true, updatedAt: true },
    });
    return rows.map((c) => ({
      url: absoluteUrl(`/category/${c.slug}`),
      lastModified: c.updatedAt,
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    }));
  } catch {
    return [];
  }
}

async function brandEntries(): Promise<MetadataRoute.Sitemap> {
  try {
    const rows = await db.brand.findMany({
      where: { isActive: true },
      select: { slug: true, updatedAt: true },
    });
    return rows.map((b) => ({
      url: absoluteUrl(`/brand/${b.slug}`),
      lastModified: b.updatedAt,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }));
  } catch {
    return [];
  }
}

async function blogEntries(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  try {
    const rows = await db.blogPost.findMany({
      where: { status: 'PUBLISHED', OR: [{ publishedAt: null }, { publishedAt: { lte: now } }] },
      select: { slug: true, updatedAt: true },
    });
    return rows.map((post) => ({
      url: absoluteUrl(`/blog/${post.slug}`),
      lastModified: post.updatedAt,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    }));
  } catch {
    return [];
  }
}

async function productEntries(page: number): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  try {
    const rows = await db.product.findMany({
      where: activeProductWhere(now),
      select: { slug: true, updatedAt: true, isFeatured: true },
      orderBy: { id: 'asc' },
      skip: Math.max(0, page) * PRODUCT_PAGE_SIZE,
      take: PRODUCT_PAGE_SIZE,
    });
    return rows.map((p) => ({
      url: absoluteUrl(`/product/${p.slug}`),
      lastModified: p.updatedAt,
      changeFrequency: 'daily' as const, // price/availability change often
      priority: p.isFeatured ? 0.9 : 0.8,
    }));
  } catch {
    return [];
  }
}

export default async function sitemap({ id }: { id?: string }): Promise<MetadataRoute.Sitemap> {
  switch (id) {
    case 'static':
      return staticEntries();
    case 'categories':
      return categoryEntries();
    case 'brands':
      return brandEntries();
    case 'blog':
      return blogEntries();
    default:
      if (id?.startsWith('products-')) {
        const page = Number(id.slice('products-'.length));
        return productEntries(Number.isFinite(page) ? page : 0);
      }
      // `/sitemap.xml` with no id (or an unknown one) — nothing to list here,
      // robots.txt is what actually points crawlers at the real section URLs.
      return [];
  }
}
